name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'mlcommons/power-dev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            oISGH1N1wIEirucX9m5ung/field/Access Token > env:INFERENCE_ACCESS_TOKEN 
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ env.INFERENCE_ACCESS_TOKEN }}  # Use PAT fetched from Keeper
          TEAM_REVIEWERS: wg-inference
          SKIP_PR: false
